#include "gray.h"
#include "sys.h"
u16 BACK_DATA	; 	
u16 RIGHT_DATA	;
u16 FRONT_DATA  ;
u16 LEFT_DATA   ;

void gray_int(void)
{
	RCC->AHB1ENR|=1<<6;//使能PORTG时钟 
	GPIO_Set(GPIOG,PIN0|PIN1|PIN2|PIN3|PIN4|PIN5|PIN6|PIN7|PIN8|PIN9|PIN10|PIN11|PIN12|PIN13|PIN14|PIN15,GPIO_MODE_IN,GPIO_OTYPE_PP,GPIO_SPEED_100M,GPIO_PUPD_NONE); //PG设置
	
	RCC->AHB1ENR|=1<<4;//使能PORTE时钟 
	GPIO_Set(GPIOE,PIN0|PIN1|PIN2|PIN3|PIN4|PIN5|PIN6|PIN7|PIN8|PIN9|PIN10|PIN11|PIN12|PIN13|PIN14|PIN15,GPIO_MODE_IN,GPIO_OTYPE_PP,GPIO_SPEED_100M,GPIO_PUPD_NONE); //PG设置

	RCC->AHB1ENR|=1<<2;//使能PORTF时钟 
	GPIO_Set(GPIOC,PIN1,GPIO_MODE_IN,GPIO_OTYPE_PP,GPIO_SPEED_100M,GPIO_PUPD_NONE); //PG设置

}

void gray_data(void)
{
	
	 LEFT_DATA  = GPIOG->IDR&0X007F;	
	 FRONT_DATA	= GPIOG->IDR>>9	;		
	 RIGHT_DATA  =  GPIOE->IDR&0X007F;	
	 BACK_DATA	= GPIOE->IDR>>9	;		

	
}
